FROM alpine:3.18

LABEL maintainer="phan@student.42seoul.kr"
LABEL version="0.0.1"
LABEL description="my nginx image"

RUN apk update
RUN apk add mariadb

# ENV MARIADB_PASSWORD=1234
# ENV MARIADB_DATABASE=1234
# ENV MARIADB_DATABASE=1234
# ENV MARIADB_DATABASE=1234

# ENTRYPOINT [ "executable" ]
