version: '3.1'

services:
  mariadb: # db
    container_name: inception-mariadb
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:phan
    volumes:
      - db_volume:/var/lib
    # environment:
    #   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    #   - MYSQL_USER=${MYSQL_USER}
    #   - MYSQL_DATABASE=${MYSQL_DATABASE}
    #   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    expose:
      - 3306
    networks:
      - inception

  wordpress: # was
    container_name: inception-wordpress
    env_file:
      - .env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:phan
    volumes:
      - web_volume:/var/www/wordpress
    # environment:
    #   - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
    #   - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
    #   - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    #   - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    #   - WORDPRESS_TABLE_PREFIX=wp_
    restart: always
    expose:
      - 9000
    depends_on:
      - mariadb
    networks:
      - inception

  nginx: # web
    container_name: inception-nginx
    env_file:
      - .env
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:phan
    volumes:
      - web_volume:/var/www/wordpress
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception

volumes:
  web_volume:
    driver: "local"
    driver_opts:
      type: none
      o: bind
      device: "/home/phan/data/wordpress"
  db_volume:
    driver: "local"
    driver_opts:
      type: none
      o: bind
      device: "/home/phan/data/db"

networks:
  inception:
    driver: bridge
