version: '3.1'

services:
  mariadb: # db
    container_name: inception-mariadb
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
        #  tags:
        #- mariadb:1.0
    image: phan/mariadb:latest
    volumes:
      - db_volume:/var/lib
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    # stdin_open: true
    # tty: true
    expose:
      - 3306
    networks:
      - inception

  wordpress: # was
    container_name: inception-wordpress
    env_file:
      - .env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
        #  tags:
        #- wordpress:1.0
    image: phan/wordpress:latest
    volumes:
      - web_volume:/var/www/wordpress
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=wp_
    restart: always
    expose:
      - 9000
    depends_on:
      - mariadb
    networks:
      - inception

  nginx: # web
    container_name: inception-nginx
    env_file:
      - .env
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
        # tags: 
        # - nginx:1.0
    image: phan/nginx:latest
    volumes:
      - web_volume:/var/www/wordpress
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception

volumes:
  web_volume:
    driver: "local"
    driver_opts:
      type: none
      o: bind
      device: "$HOME/docker/wordpress"
  db_volume:
    driver: "local"
    driver_opts:
      type: none
      o: bind
      device: "$HOME/docker/db"

networks:
  inception:
    driver: bridge
